language: java
jdk:
  - oraclejdk8
before_install:
  - npm i -g npm@3
  - npm install -g bower
node_js: "6"
install:
  - cd pet-client
  - bower install
  - npm install
script:
  - cd ..
  - mvn install
  - cd pet-client
  - npm test